packages:
  - "packages/liquity"
  - "packages/algebra"
  - "packages/morpho"
  - "packages/erc-8004"
  - "packages/shared"
  - "packages/yield"
  - "packages/oracle"
  - "packages/options"
  - "packages/frontend"
