// Snowball DEX — Algebra V4 Integral fork ABIs (BUSL-1.1)

export const SnowballFactoryABI = [
  "function owner() view returns (address)",
  "function pendingOwner() view returns (address)",
  "function poolDeployer() view returns (address)",
  "function defaultPluginFactory() view returns (address)",
  "function vaultFactory() view returns (address)",
  "function defaultCommunityFee() view returns (uint16)",
  "function defaultFee() view returns (uint16)",
  "function defaultTickspacing() view returns (int24)",
  "function POOL_INIT_CODE_HASH() view returns (bytes32)",
  "function POOLS_ADMINISTRATOR_ROLE() view returns (bytes32)",
  "function CUSTOM_POOL_DEPLOYER() view returns (bytes32)",
  "function renounceOwnershipStartTimestamp() view returns (uint256)",
  "function poolByPair(address, address) view returns (address)",
  "function customPoolByPair(address, address, address) view returns (address)",
  "function computePoolAddress(address token0, address token1) view returns (address pool)",
  "function computeCustomPoolAddress(address deployer, address token0, address token1) view returns (address customPool)",
  "function defaultConfigurationForPool() view returns (uint16 communityFee, int24 tickSpacing, uint16 fee)",
  "function hasRoleOrOwner(bytes32 role, address account) view returns (bool)",
  "function hasRole(bytes32 role, address account) view returns (bool)",
  "function getRoleMember(bytes32 role, uint256 index) view returns (address)",
  "function getRoleMemberCount(bytes32 role) view returns (uint256)",
  "function createPool(address tokenA, address tokenB, bytes data) returns (address pool)",
  "function createCustomPool(address deployer, address creator, address tokenA, address tokenB, bytes data) returns (address customPool)",
  "function setDefaultCommunityFee(uint16 newDefaultCommunityFee)",
  "function setDefaultFee(uint16 newDefaultFee)",
  "function setDefaultTickspacing(int24 newDefaultTickspacing)",
  "function setDefaultPluginFactory(address newDefaultPluginFactory)",
  "function setVaultFactory(address newVaultFactory)",
  "function grantRole(bytes32 role, address account)",
  "function revokeRole(bytes32 role, address account)",
  "function transferOwnership(address newOwner)",
  "function acceptOwnership()",
  "function startRenounceOwnership()",
  "function stopRenounceOwnership()",
  "function renounceOwnership()",
  "event Pool(address indexed token0, address indexed token1, address pool)",
  "event CustomPool(address indexed deployer, address indexed token0, address indexed token1, address pool)",
  "event DefaultCommunityFee(uint16 newDefaultCommunityFee)",
  "event DefaultFee(uint16 newDefaultFee)",
  "event DefaultTickspacing(int24 newDefaultTickspacing)",
  "event DefaultPluginFactory(address defaultPluginFactoryAddress)",
  "event VaultFactory(address newVaultFactory)",
  "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
  "event OwnershipTransferStarted(address indexed previousOwner, address indexed newOwner)",
  "event RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)",
  "event RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)",
] as const;

export const SnowballPoolABI = [
  "function token0() view returns (address)",
  "function token1() view returns (address)",
  "function factory() view returns (address)",
  "function plugin() view returns (address)",
  "function communityVault() view returns (address)",
  "function tickSpacing() view returns (int24)",
  "function fee() view returns (uint16 currentFee)",
  "function liquidity() view returns (uint128)",
  "function maxLiquidityPerTick() view returns (uint128)",
  "function totalFeeGrowth0Token() view returns (uint256)",
  "function totalFeeGrowth1Token() view returns (uint256)",
  "function prevTickGlobal() view returns (int24)",
  "function nextTickGlobal() view returns (int24)",
  "function tickTreeRoot() view returns (uint32)",
  "function lastFeeTransferTimestamp() view returns (uint32)",
  "function globalState() view returns (uint160 price, int24 tick, uint16 lastFee, uint8 pluginConfig, uint16 communityFee, bool unlocked)",
  "function isUnlocked() view returns (bool unlocked)",
  "function safelyGetStateOfAMM() view returns (uint160 sqrtPrice, int24 tick, uint16 lastFee, uint8 pluginConfig, uint128 activeLiquidity, int24 nextTick, int24 previousTick)",
  "function positions(bytes32) view returns (uint256 liquidity, uint256 innerFeeGrowth0Token, uint256 innerFeeGrowth1Token, uint128 fees0, uint128 fees1)",
  "function ticks(int24) view returns (uint256 liquidityTotal, int128 liquidityDelta, int24 prevTick, int24 nextTick, uint256 outerFeeGrowth0Token, uint256 outerFeeGrowth1Token)",
  "function tickTable(int16) view returns (uint256)",
  "function tickTreeSecondLayer(int16) view returns (uint256)",
  "function getReserves() view returns (uint128, uint128)",
  "function getCommunityFeePending() view returns (uint128, uint128)",
  "function getPluginFeePending() view returns (uint128, uint128)",
  "function initialize(uint160 initialPrice)",
  "function mint(address leftoversRecipient, address recipient, int24 bottomTick, int24 topTick, uint128 liquidityDesired, bytes data) returns (uint256 amount0, uint256 amount1, uint128 liquidityActual)",
  "function burn(int24 bottomTick, int24 topTick, uint128 amount, bytes data) returns (uint256 amount0, uint256 amount1)",
  "function collect(address recipient, int24 bottomTick, int24 topTick, uint128 amount0Requested, uint128 amount1Requested) returns (uint128 amount0, uint128 amount1)",
  "function swap(address recipient, bool zeroToOne, int256 amountRequired, uint160 limitSqrtPrice, bytes data) returns (int256 amount0, int256 amount1)",
  "function swapWithPaymentInAdvance(address leftoversRecipient, address recipient, bool zeroToOne, int256 amountToSell, uint160 limitSqrtPrice, bytes data) returns (int256 amount0, int256 amount1)",
  "function flash(address recipient, uint256 amount0, uint256 amount1, bytes data)",
  "function skim()",
  "function sync()",
  "function setPlugin(address newPluginAddress)",
  "function setPluginConfig(uint8 newConfig)",
  "function setFee(uint16 newFee)",
  "function setTickSpacing(int24 newTickSpacing)",
  "function setCommunityFee(uint16 newCommunityFee)",
  "function setCommunityVault(address newCommunityVault)",
  "event Initialize(uint160 price, int24 tick)",
  "event Mint(address sender, address indexed owner, int24 indexed bottomTick, int24 indexed topTick, uint128 liquidityAmount, uint256 amount0, uint256 amount1)",
  "event Burn(address indexed owner, int24 indexed bottomTick, int24 indexed topTick, uint128 liquidityAmount, uint256 amount0, uint256 amount1)",
  "event Swap(address indexed sender, address indexed recipient, int256 amount0, int256 amount1, uint160 price, uint128 liquidity, int24 tick)",
  "event SwapFee(address indexed sender, uint24 overrideFee, uint24 pluginFee)",
  "event BurnFee(address indexed owner, uint24 pluginFee)",
  "event Collect(address indexed owner, address recipient, int24 indexed bottomTick, int24 indexed topTick, uint128 amount0, uint128 amount1)",
  "event Flash(address indexed sender, address indexed recipient, uint256 amount0, uint256 amount1, uint256 paid0, uint256 paid1)",
  "event Fee(uint16 fee)",
  "event TickSpacing(int24 newTickSpacing)",
  "event Plugin(address newPluginAddress)",
  "event PluginConfig(uint8 newPluginConfig)",
  "event CommunityFee(uint16 communityFeeNew)",
  "event CommunityVault(address newCommunityVault)",
  "event ExcessTokens(uint256 amount0, uint256 amount1)",
  "event Skim(address indexed to, uint256 amount0, uint256 amount1)",
] as const;

export const SnowballRouterABI = [
  "function factory() view returns (address)",
  "function WNativeToken() view returns (address)",
  "function poolDeployer() view returns (address)",
  "function exactInputSingle((address tokenIn, address tokenOut, address deployer, address recipient, uint256 deadline, uint256 amountIn, uint256 amountOutMinimum, uint160 limitSqrtPrice) params) payable returns (uint256 amountOut)",
  "function exactInput((bytes path, address recipient, uint256 deadline, uint256 amountIn, uint256 amountOutMinimum) params) payable returns (uint256 amountOut)",
  "function exactOutputSingle((address tokenIn, address tokenOut, address deployer, address recipient, uint256 deadline, uint256 amountOut, uint256 amountInMaximum, uint160 limitSqrtPrice) params) payable returns (uint256 amountIn)",
  "function exactOutput((bytes path, address recipient, uint256 deadline, uint256 amountOut, uint256 amountInMaximum) params) payable returns (uint256 amountIn)",
  "function exactInputSingleSupportingFeeOnTransferTokens((address tokenIn, address tokenOut, address deployer, address recipient, uint256 deadline, uint256 amountIn, uint256 amountOutMinimum, uint160 limitSqrtPrice) params) payable returns (uint256 amountOut)",
  "function sweepToken(address token, uint256 amountMinimum, address recipient) payable",
  "function sweepTokenWithFee(address token, uint256 amountMinimum, address recipient, uint256 feeBips, address feeRecipient) payable",
  "function unwrapWNativeToken(uint256 amountMinimum, address recipient) payable",
  "function unwrapWNativeTokenWithFee(uint256 amountMinimum, address recipient, uint256 feeBips, address feeRecipient) payable",
  "function refundNativeToken() payable",
  "function multicall(bytes[] data) payable returns (bytes[] results)",
  "function selfPermit(address token, uint256 value, uint256 deadline, uint8 v, bytes32 r, bytes32 s) payable",
  "function selfPermitIfNecessary(address token, uint256 value, uint256 deadline, uint8 v, bytes32 r, bytes32 s) payable",
  "function selfPermitAllowed(address token, uint256 nonce, uint256 expiry, uint8 v, bytes32 r, bytes32 s) payable",
  "function selfPermitAllowedIfNecessary(address token, uint256 nonce, uint256 expiry, uint8 v, bytes32 r, bytes32 s) payable",
  "function algebraSwapCallback(int256 amount0Delta, int256 amount1Delta, bytes _data)",
] as const;

export const SnowballPoolDeployerABI = [
  "function getDeployParameters() view returns (address _plugin, address _factory, address _token0, address _token1)",
  "function deploy(address plugin, address token0, address token1, address deployer) returns (address pool)",
] as const;

export const NonfungiblePositionManagerABI = [
  "function factory() view returns (address)",
  "function WNativeToken() view returns (address)",
  "function poolDeployer() view returns (address)",
  "function positions(uint256 tokenId) view returns (uint88 nonce, address operator, address token0, address token1, address deployer, int24 tickLower, int24 tickUpper, uint128 liquidity, uint256 feeGrowthInside0LastX128, uint256 feeGrowthInside1LastX128, uint128 tokensOwed0, uint128 tokensOwed1)",
  "function createAndInitializePoolIfNecessary(address token0, address token1, address deployer, uint160 sqrtPriceX96, bytes data) payable returns (address pool)",
  "function mint((address token0, address token1, address deployer, int24 tickLower, int24 tickUpper, uint256 amount0Desired, uint256 amount1Desired, uint256 amount0Min, uint256 amount1Min, address recipient, uint256 deadline) params) payable returns (uint256 tokenId, uint128 liquidity, uint256 amount0, uint256 amount1)",
  "function increaseLiquidity((uint256 tokenId, uint256 amount0Desired, uint256 amount1Desired, uint256 amount0Min, uint256 amount1Min, uint256 deadline) params) payable returns (uint128 liquidity, uint256 amount0, uint256 amount1)",
  "function decreaseLiquidity((uint256 tokenId, uint128 liquidity, uint256 amount0Min, uint256 amount1Min, uint256 deadline) params) payable returns (uint256 amount0, uint256 amount1)",
  "function collect((uint256 tokenId, address recipient, uint128 amount0Max, uint128 amount1Max) params) payable returns (uint256 amount0, uint256 amount1)",
  "function burn(uint256 tokenId) payable",
  "function approve(address to, uint256 tokenId)",
  "function setApprovalForAll(address operator, bool approved)",
  "function getApproved(uint256 tokenId) view returns (address)",
  "function isApprovedForAll(address owner, address operator) view returns (bool)",
  "function balanceOf(address owner) view returns (uint256)",
  "function ownerOf(uint256 tokenId) view returns (address)",
  "function tokenOfOwnerByIndex(address owner, uint256 index) view returns (uint256)",
  "function totalSupply() view returns (uint256)",
  "function tokenByIndex(uint256 index) view returns (uint256)",
  "function tokenURI(uint256 tokenId) view returns (string)",
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function multicall(bytes[] data) payable returns (bytes[] results)",
  "function sweepToken(address token, uint256 amountMinimum, address recipient) payable",
  "function unwrapWNativeToken(uint256 amountMinimum, address recipient) payable",
  "function refundNativeToken() payable",
  "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)",
  "event Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)",
  "event ApprovalForAll(address indexed owner, address indexed operator, bool approved)",
  "event IncreaseLiquidity(uint256 indexed tokenId, uint128 liquidityDesired, uint128 actualLiquidity, uint256 amount0, uint256 amount1, address pool)",
  "event DecreaseLiquidity(uint256 indexed tokenId, uint128 liquidity, uint256 amount0, uint256 amount1)",
  "event Collect(uint256 indexed tokenId, address recipient, uint256 amount0, uint256 amount1)",
] as const;

export const QuoterV2ABI = [
  "function factory() view returns (address)",
  "function WNativeToken() view returns (address)",
  "function poolDeployer() view returns (address)",
  "function quoteExactInputSingle((address tokenIn, address tokenOut, address deployer, uint256 amountIn, uint160 limitSqrtPrice) params) returns (uint256 amountOut, uint256 amountIn, uint160 sqrtPriceX96After, uint32 initializedTicksCrossed, uint256 gasEstimate, uint16 fee)",
  "function quoteExactInput(bytes path, uint256 amountInRequired) returns (uint256[] amountOutList, uint256[] amountInList, uint160[] sqrtPriceX96AfterList, uint32[] initializedTicksCrossedList, uint256 gasEstimate, uint16[] feeList)",
  "function quoteExactOutputSingle((address tokenIn, address tokenOut, address deployer, uint256 amount, uint160 limitSqrtPrice) params) returns (uint256 amountOut, uint256 amountIn, uint160 sqrtPriceX96After, uint32 initializedTicksCrossed, uint256 gasEstimate, uint16 fee)",
  "function quoteExactOutput(bytes path, uint256 amountOutRequired) returns (uint256[] amountOutList, uint256[] amountInList, uint160[] sqrtPriceX96AfterList, uint32[] initializedTicksCrossedList, uint256 gasEstimate, uint16[] feeList)",
] as const;

export const DynamicFeePluginABI = [
  "function factory() view returns (address)",
  "function owner() view returns (address)",
  "function poolConfig(address pool) view returns (uint16 minFee, uint16 maxFee, uint32 volatilityWindow, bool registered)",
  "function pluginForPool(address pool) view returns (address)",
  "function defaultPluginConfig() view returns (uint8)",
  "function getCurrentFee() view returns (uint16 fee)",
  "function getFee(address pool) view returns (uint16)",
  "function setOwner(address _owner)",
  "function registerPool(address pool, uint16 minFee, uint16 maxFee, uint32 volatilityWindow)",
  "function beforeCreatePoolHook(address pool, address creator, address deployer, address token0, address token1, bytes data) returns (address)",
  "function afterCreatePoolHook(address plugin, address pool, address deployer)",
  "function beforeSwap(address sender, address recipient, bool zeroToOne, int256 amountRequired, uint160 limitSqrtPrice, bool withPaymentInAdvance, bytes data) returns (bytes4 selector, uint24 feeOverride, uint24 pluginFee)",
  "event PluginRegistered(address indexed pool, uint16 minFee, uint16 maxFee)",
  "event FeeUpdated(address indexed pool, uint16 newFee)",
  "event OwnerChanged(address indexed newOwner)",
] as const;
